plugins:
  - rubocop-graphql

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

GraphQL/ObjectDescription:
  Enabled: true
  Exclude:
    - 'app/graphql/myapp_schema.rb'
    - 'app/graphql/loaders/active_storage_loader.rb'
    - 'app/graphql/loaders/association_loader.rb'
    - 'app/graphql/my_timeout.rb'
    - 'app/graphql/types/node_type.rb'
    - 'app/graphql/types/base_object.rb'
    - 'app/graphql/types/base_field.rb'
    - 'app/graphql/types/base_connection.rb'
    - 'app/graphql/types/base_argument.rb'
    - 'app/graphql/types/base_resolver.rb'
    - 'app/graphql/types/base_union.rb'
    - 'app/graphql/types/base_scalar.rb'
    - 'app/graphql/types/base_interface.rb'
    - 'app/graphql/types/base_input_object.rb'
    - 'app/graphql/types/base_enum.rb'
    - 'app/graphql/types/base_edge.rb'
    - 'app/graphql/mutations/base_mutation.rb'
    - 'app/graphql/resolvers/base_resolver.rb'

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: true

GraphQL/ExtractType:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: true

GraphQL/ResolverMethodLength:
  Max: 15
