openapi: 3.0.3
info:
  title: 投稿API
  description: ブログ投稿に関するAPI仕様
  version: 1.0.0
servers:
  - url: /api
    description: Default API server
paths:
  /v1/posts:
    get:
      summary: 公開された投稿一覧を取得
      description: すべての公開投稿を日付の新しい順に取得します
      operationId: getPosts
      parameters:
        - name: page
          in: query
          description: "ページ番号（デフォルト: 1）"
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: 正常にデータが取得できた場合
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          description: 投稿ID
        title:
          type: string
          description: 投稿タイトル
        content:
          type: string
          description: 投稿内容
        published:
          type: boolean
          description: 公開ステータス
        user_id:
          type: integer
          description: 投稿者のユーザーID
        created_at:
          type: string
          format: date-time
          description: 作成日時
        updated_at:
          type: string
          format: date-time
          description: 更新日時
        thumbnail_url:
          type: string
          nullable: true
          description: サムネイル画像のURL
      required:
        - id
        - title
        - content
        - published
        - user_id
        - created_at
        - updated_at
    Error:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
      required:
        - error
