# frozen_string_literal: true

module Types
  class UserError < Types::BaseObject
    description "Errors generated by user operations"

    field :message, String, null: false, description: "Error message"
    field :path, [String], null: true, description: "Path to the location of the error"
  end
end
