name: Update GraphQL Schema

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/graphql/**/*.rb'

jobs:
  update-schema:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose build

      - name: Generate GraphQL schema
        run: docker compose run --rm web bundle exec rails graphql:schema:json

      - name: Check for schema changes
        id: git-check
        run: |
          git add schema.json
          git diff --staged --quiet schema.json || echo "schema_changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push schema changes
        if: steps.git-check.outputs.schema_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: Update GraphQL schema" schema.json
          git push origin HEAD:${{ github.head_ref }}
